package frame;



import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author LENOVO IDEAPAD 110
 */
public class Project_BP1 extends javax.swing.JFrame {

    JasperReport jasperReport;
    JasperPrint jasperPrint;
    Map param = new HashMap<>();
    JasperDesign jasperDesign;

    Statement st;
    ResultSet rs;
    PreparedStatement prep;
    konektor connector;

    /**
     * Creates new form Project_BP1
     */
    public Project_BP1() {
        connector = new konektor();
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaBarangField = new javax.swing.JTextField();
        kategoriField = new javax.swing.JTextField();
        hargaField = new javax.swing.JTextField();
        jumlahStokField = new javax.swing.JTextField();
        tambahBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        bersihBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText(" Manajemen Stok Barang AK Cell");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama Barang", "Kategori", "Harga", "Jumlah Stok"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Nama Barang:");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("Kategori:");

        jLabel4.setText("Harga:");

        jLabel5.setText("Jumlah Stok:");

        jumlahStokField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahStokFieldActionPerformed(evt);
            }
        });

        tambahBtn.setBackground(new java.awt.Color(153, 204, 255));
        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(204, 204, 204));
        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });

        hapusBtn.setBackground(new java.awt.Color(255, 51, 51));
        hapusBtn.setText("Hapus");
        hapusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusBtnMouseClicked(evt);
            }
        });

        bersihBtn.setBackground(new java.awt.Color(51, 255, 0));
        bersihBtn.setText("Bersihkan");
        bersihBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Cetak Laporan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setText("Cari");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(157, 157, 157))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(149, 149, 149)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(tambahBtn)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bersihBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(namaBarangField)
                    .addComponent(hargaField)
                    .addComponent(jumlahStokField)
                    .addComponent(kategoriField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kategoriField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambahBtn)
                            .addComponent(updateBtn)
                            .addComponent(hapusBtn)
                            .addComponent(bersihBtn)
                            .addComponent(jButton1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jumlahStokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahStokFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahStokFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahStokFieldActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
        create();
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Label diklik.");

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        {
            int selectedRow = jTable1.getSelectedRow();

            String nama = jTable1.getValueAt(selectedRow, 1).toString();
            String kategori = jTable1.getValueAt(selectedRow, 2).toString();
            String harga = jTable1.getValueAt(selectedRow, 3).toString();
            String jumlahStok = jTable1.getValueAt(selectedRow, 4).toString();

            namaBarangField.setText(nama);
            kategoriField.setText(kategori);
            hargaField.setText(harga);
            jumlahStokField.setText(jumlahStok);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        edit();        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnMouseClicked

    private void hapusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusBtnMouseClicked
        delete();        // TODO add your handling code here:
    }//GEN-LAST:event_hapusBtnMouseClicked

    private void bersihBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihBtnActionPerformed
        clear();      // TODO add your handling code here:
    }//GEN-LAST:event_bersihBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
            File file = new File("C:\\Users\\LENOVO IDEAPAD 110\\Documents\\NetBeansProjects\\ProjectBP1\\src\\frame\\report1.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            param.clear();
            
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param, connector.connect);
            
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            
            jasperViewer.setVisible(true);
        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, err);
        }    // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        searchQueryRows();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void load() {
        String sql = "SELECT * FROM barang";

        try {
            st = connector.connect.createStatement();
            rs = st.executeQuery(sql);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int column1 = rs.getInt("id");
                String column2 = rs.getString("nama_barang");
                String column3 = rs.getString("kategori");
                Float column4 = rs.getFloat("harga");
                int column5 = rs.getInt("jumlah_stok");

                model.addRow(new Object[]{column1, column2, column3, column4, column5});

            }
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err);
        }
    }

    private void create() {
        String sql = "INSERT INTO barang (nama_barang, kategori, harga, jumlah_stok) VALUES(?, ?, ?, ?)";
        try {
            prep = connector.connect.prepareStatement(sql);

            prep.setString(1, namaBarangField.getText());
            prep.setString(2, kategoriField.getText());
            prep.setFloat(3, Float.parseFloat(hargaField.getText()));
            prep.setInt(4, Integer.parseInt(jumlahStokField.getText()));

            int rowsUpdated = prep.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diinput.");
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, data gagal diinput.");
            }
            load();

        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err);
        }
    }

    private void edit() {
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah anda yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.NO_OPTION) {
            return;
        }

        String sql = "UPDATE barang SET nama_barang = ?, kategori = ?, harga = ?, jumlah_stok = ? WHERE id = ?";

        try {
            int selectedRow = jTable1.getSelectedRow();
            String id = jTable1.getValueAt(selectedRow, 0).toString();

            prep = connector.connect.prepareStatement(sql);

            prep.setString(1, namaBarangField.getText());
            prep.setString(2, kategoriField.getText());
            prep.setFloat(3, Float.parseFloat(hargaField.getText()));
            prep.setInt(4, Integer.parseInt(jumlahStokField.getText()));
            prep.setInt(5, Integer.parseInt(id));

            int rowsUpdated = prep.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil di update.");
            } else {
                JOptionPane.showMessageDialog(null, "Data gagal di update.");
            }

            load();
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err);
        }
    }

    private void delete() {
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah anda yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.NO_OPTION) {
            return;
        }

        String sql = "DELETE FROM barang WHERE id = ?";

        try {
            prep = connector.connect.prepareStatement(sql);

            int selectedRow = jTable1.getSelectedRow();
            String id = jTable1.getValueAt(selectedRow, 0).toString();

            prep.setString(1, id);

            int rowsUpdated = prep.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil di delete.");
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, data gagal di delete.");
            }

            load();
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err);
        }
    }

    private void clear() {
        namaBarangField.setText("");
        kategoriField.setText("");
        hargaField.setText("");
        jumlahStokField.setText("");

        jTable1.clearSelection();

        JOptionPane.showMessageDialog(null, "Form telah dibersihkan.");
    }
    
    private int searchQueryRows() {
    String sql = "SELECT * FROM barang WHERE "
            + "(? = '' OR LOWER(nama_barang) LIKE ?) AND "
            + "(? = '' OR LOWER(kategori) LIKE ?) AND "
            + "(? = '' OR LOWER(harga) LIKE ?) AND "
            + "(? = '' OR LOWER(jumlah_stok) LIKE ?)";

    int result = 0;

    
        try {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        prep = connector.connect.prepareStatement(sql);

        prep.setString(1, namaBarangField.getText());
        prep.setString(2, "%" + namaBarangField.getText() + "%");
        prep.setString(3, kategoriField.getText());
        prep.setString(4, "%" + kategoriField.getText() + "%");
        prep.setString(5, hargaField.getText());
        prep.setString(6, "%" + hargaField.getText() + "%");
        prep.setString(7, jumlahStokField.getText());
        prep.setString(8, "%" + jumlahStokField.getText() + "%");

        rs = prep.executeQuery();

        while (rs.next()) {
            String id = rs.getString("id");
            String nama_barang = rs.getString("nama_barang");
            String kategori = rs.getString("kategori");
            String harga = rs.getString("harga");
            String jumlah_stok = rs.getString("jumlah_stok");

            model.addRow(new Object[]{id, nama_barang, kategori, harga, jumlah_stok});
            result = 1;
        }

    }
    catch (Exception err

    
        ) {
            JOptionPane.showMessageDialog(this, err);
    }

    return result ;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project_BP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project_BP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project_BP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project_BP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project_BP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField hargaField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlahStokField;
    private javax.swing.JTextField kategoriField;
    private javax.swing.JTextField namaBarangField;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
